import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideNav from "../components/SideNav/SideNav";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function TopicLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const secondaryLinks = [
        {
            label: "Sub Topic 1",
            linkHeader: "sub-topic-one",
            href: "/topic-one/sub-topic-one/",
            tertiaryLinks: [
                {
                    href: '/topic-one/sub-topic-one/sub-sub-topic-one',
                    label: "sub-sub-topic-one",
                    linkHeader: "sub-sub-topic-one"
                },
                {
                    href: '/topic-one/sub-topic-one/sub-sub-topic-two',
                    label: "sub-sub-topic-two",
                    linkHeader: "sub-sub-topic-two"
                }
            ]
        },
        {
            label: "Sub Topic 2",
            linkHeader: "sub-topic-two",
            href: "/topic-one/sub-topic-two/",
            tertiaryLinks: [
                {
                    href: '/topic-one/sub-topic-two/sub-sub-topic-one',
                    label: "sub-sub-topic-one",
                    linkHeader: "sub-sub-topic-one"
                },
                {
                    href: '/topic-one/sub-topic-two/sub-sub-topic-two',
                    label: "sub-sub-topic-two",
                    linkHeader: "sub-sub-topic-two"
                }
            ]
        },

    ]

    return (

        <div className="flex">
            <SideNav 
                secondaryLinks={secondaryLinks}
            />
            <div className="p-2" style={{ width: '100%' }}>
                {children}
            </div>
        </div>
    );
}
